# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-04 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginningYear', models.IntegerField()),
                ('endingYear', models.IntegerField()),
                ('semesterType', models.IntegerField(choices=[(1, 'پاییز'), (2, 'بهار'), (3, 'تابستان')])),
            ],
        ),
        migrations.RenameField(
            model_name='defenseplace',
            old_name='BuildingName',
            new_name='buildingName',
        ),
        migrations.RenameField(
            model_name='defenseplace',
            old_name='PlaceName',
            new_name='placeName',
        ),
        migrations.RenameField(
            model_name='defenseplace',
            old_name='RoomName',
            new_name='roomName',
        ),
        migrations.AddField(
            model_name='defenseplace',
            name='semester',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='main.Semester'),
            preserve_default=False,
        ),
    ]
