# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180510_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defensetime',
            old_name='defensePlace',
            new_name='defense_place',
        ),
    ]
